### ISSUE TITLE
怎么使用k-means优化anchors-box设置？

### ISSUE THREAD

**Issue by zqdeepbluesky** [lars76/kmeans-anchor-boxes#2]
你好，代码写的很棒。
只是我想知道如何通过它来进行anchor的优化，例如我现在已经知道了设置5个anchor-boxs的效果要比faster-rcnn通过ratio设置的9个anchor-box好。
如果我想使用k-means来优化我的anchor-box设置，是通过ratio来增加anchor-box的个数吗，那么我如何得到ratio呢？我想知道你的聚类结果中有没有显示各聚类中的大致尺寸比例？
再次非常感谢。祝你一切顺利。

**Comment by lars76** [comment]
Hi, how you use the anchor boxes generated by the algorithm depends on your Faster R-CNN (RPN) implementation. I have never tested it with R-CNN, but I'll give you an example, what you can do.

If I run the algorithm on VOC2007, I obtain the following anchor boxes:

[[0.792      0.776     ]
 [0.098      0.16516517]
 [0.042      0.07466667]
 [0.38133333 0.52535323]
 [0.184      0.33866667]]

We can now divide width by height, to obtain the aspect ratios:

[[1.0206185567, 0.59334543717, 0.56249997488, 0.72586082701, 0.54330708126]]

Then you can use in your sliding window these or similar ratios.

Thus, the cluster algorithm doesn't provide the scale of the objects, only the individual widths/heights. In the YOLOv3 paper, the authors write: "We [...] chose 9 clusters and 3 scales arbitrarily and then divide up the clusters evenly across scales." Hopefully, this answered your questions.

**Comment by zqdeepbluesky** [comment]
非常感谢你的回答，我会尝试在faster rcnn上使用这种宽高比的设置，再次非常感谢，祝你生活愉快！！！

**Comment by zqdeepbluesky** [comment]
@lars76 
hi,when I test my dataset in your code,I met error:
dxt@dxt-System-Product-Name:~/kmeans-anchor-boxes-master$ python3 -m unittest discover -s tests/
............EE
======================================================================
ERROR: test_kmeans_5 (test_voc2007.TestVoc2007)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dxt/kmeans-anchor-boxes-master/tests/test_voc2007.py", line 34, in test_kmeans_5
    out = kmeans(dataset, 5)
  File "/home/dxt/kmeans-anchor-boxes-master/kmeans.py", line 64, in kmeans
    clusters = boxes[np.random.choice(rows, k, replace=False)]
  File "mtrand.pyx", line 1115, in mtrand.RandomState.choice
ValueError: a must be greater than 0

======================================================================
ERROR: test_kmeans_9 (test_voc2007.TestVoc2007)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dxt/kmeans-anchor-boxes-master/tests/test_voc2007.py", line 42, in test_kmeans_9
    out = kmeans(dataset, 9)
  File "/home/dxt/kmeans-anchor-boxes-master/kmeans.py", line 64, in kmeans
    clusters = boxes[np.random.choice(rows, k, replace=False)]
  File "mtrand.pyx", line 1115, in mtrand.RandomState.choice
ValueError: a must be greater than 0

----------------------------------------------------------------------
Ran 14 tests in 0.013s

FAILED (errors=2)

I don't know how to solve it,can you tell me what should I do to fix it? thanks so much.

**Comment by txytju** [comment]
@zqdeepbluesky 请问在 faster rcnn 上使用聚类后的高宽比设置之后效果怎么样？

**Comment by txytju** [comment]
@lars76 I think in faster rcnn, not only the ratios are useful, but also the actual sizes. For grounding truth bounding boxes in the reshaped images(which are reshaped to 600*height), you can caculate the clustering of actual length rather than the ratios like height_of_bounding_box/height_of_reshaped_image.

**Comment by zqdeepbluesky** [comment]
@txytju 
我得到的效果不明显，主要想了解一下它是否能够加速收敛，在原始yolov2中也是这个作用，你提到的将原始宽高比替换比例尺，可能效果要好一些吧，可以尝试一下。
